export enum ROLES {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum ENTITIES {
  USERS = 'users',
  PROFILES = 'profiles',
  INCOMES = 'incomes',
  EXPENSES = 'expenses',
  INVESTMENTS = 'investments',
  SUBSCRIPTIONS = 'subscriptions',
  DEBTS = 'debts',
  LENDS = 'lends',
  REPORTS = 'reports',
  NOTIFIERS = 'notifiers',
  FEEDBACKS = 'feedbacks',
  CATEGORIES = 'categories',
}

export const Actions = {
  [ENTITIES.USERS]: {
    canCreate: 'CREATE_USERS',
    canRead: 'READ_USERS',
    canReadAll: 'READ_ALL_USERS',
    canUpdate: 'UPDATE_USERS',
    canDelete: 'DELETE_USERS',
  },
  [ENTITIES.PROFILES]: {
    canCreate: 'CREATE_PROFILES',
    canRead: 'READ_PROFILES',
    canReadAll: 'READ_ALL_PROFILES',
    canUpdate: 'UPDATE_PROFILES',
    canDelete: 'DELETE_PROFILES',
  },
  [ENTITIES.CATEGORIES]: {
    canCreate: 'CREATE_CATEGORIES',
    canRead: 'READ_CATEGORIES',
    canReadAll: 'READ_ALL_CATEGORIES',
    canUpdate: 'UPDATE_CATEGORIES',
    canDelete: 'DELETE_CATEGORIES',
  },
  [ENTITIES.INCOMES]: {
    canCreate: 'CREATE_INCOMES',
    canRead: 'READ_INCOMES',
    canReadAll: 'READ_ALL_INCOMES',
    canUpdate: 'UPDATE_INCOMES',
    canDelete: 'DELETE_INCOMES',
  },
  [ENTITIES.EXPENSES]: {
    canCreate: 'CREATE_EXPENSES',
    canRead: 'READ_EXPENSES',
    canReadAll: 'READ_ALL_EXPENSES',
    canUpdate: 'UPDATE_EXPENSES',
    canDelete: 'DELETE_EXPENSES',
  },
  [ENTITIES.DEBTS]: {
    canCreate: 'CREATE_DEBTS',
    canRead: 'READ_DEBTS',
    canReadAll: 'READ_ALL_DEBTS',
    canUpdate: 'UPDATE_DEBTS',
    canDelete: 'DELETE_DEBTS',
  },
  [ENTITIES.LENDS]: {
    canCreate: 'CREATE_LENDS',
    canRead: 'READ_LENDS',
    canReadAll: 'READ_ALL_LENDS',
    canUpdate: 'UPDATE_LENDS',
    canDelete: 'DELETE_LENDS',
  },
  [ENTITIES.INVESTMENTS]: {
    canCreate: 'CREATE_INVESTMENTS',
    canRead: 'READ_INVESTMENTS',
    canReadAll: 'READ_ALL_INVESTMENTS',
    canUpdate: 'UPDATE_INVESTMENTS',
    canDelete: 'DELETE_INVESTMENTS',
  },
  [ENTITIES.SUBSCRIPTIONS]: {
    canCreate: 'CREATE_SUBSCRIPTIONS',
    canRead: 'READ_SUBSCRIPTIONS',
    canReadAll: 'READ_ALL_SUBSCRIPTIONS',
    canUpdate: 'UPDATE_SUBSCRIPTIONS',
    canDelete: 'DELETE_SUBSCRIPTIONS',
  },
  [ENTITIES.NOTIFIERS]: {
    canCreate: 'CREATE_NOTIFIERS',
    canRead: 'READ_NOTIFIERS',
    canReadAll: 'READ_ALL_NOTIFIERS',
    canUpdate: 'UPDATE_NOTIFIERS',
    canDelete: 'DELETE_NOTIFIERS',
  },
  [ENTITIES.REPORTS]: {
    canCreate: 'CREATE_REPORTS',
    canRead: 'READ_REPORTS',
    canReadAll: 'READ_ALL_REPORTS',
    canUpdate: 'UPDATE_REPORTS',
    canDelete: 'DELETE_REPORTS',
  },
  [ENTITIES.FEEDBACKS]: {
    canCreate: 'CREATE_FEEDBACKS',
    canRead: 'READ_FEEDBACKS',
    canReadAll: 'READ_ALL_FEEDBACKS',
    canUpdate: 'UPDATE_FEEDBACKS',
    canDelete: 'DELETE_FEEDBACKS',
  },
};

export const RolePermissions = {
  [ROLES.USER]: {
    [ENTITIES.USERS]: [Actions.users.canRead, Actions.users.canUpdate],
    [ENTITIES.PROFILES]: [],
    [ENTITIES.CATEGORIES]: [],
    [ENTITIES.INCOMES]: [],
    [ENTITIES.EXPENSES]: [],
    [ENTITIES.DEBTS]: [],
    [ENTITIES.LENDS]: [],
    [ENTITIES.INVESTMENTS]: [],
    [ENTITIES.SUBSCRIPTIONS]: [],
    [ENTITIES.NOTIFIERS]: [],
    [ENTITIES.REPORTS]: [],
    [ENTITIES.FEEDBACKS]: [],
  },
  [ROLES.ADMIN]: {
    [ENTITIES.USERS]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.PROFILES]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.CATEGORIES]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.INCOMES]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.EXPENSES]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.DEBTS]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.LENDS]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.INVESTMENTS]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.SUBSCRIPTIONS]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.NOTIFIERS]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.REPORTS]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
    [ENTITIES.FEEDBACKS]: [
      Actions.users.canCreate,
      Actions.users.canRead,
      Actions.users.canReadAll,
      Actions.users.canUpdate,
      Actions.users.canDelete,
    ],
  },
};
